### ISSUE TITLE
Router example

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [litelement-dev/create-lit#5]
Hi @dvalinotti, I'm starting to explore lit and I was keen on getting vite support, so happy with this contribution – cool stuff! I also like to better understand routing, SSR and see how minimum hydration would take place. Wonder if you're interested in adding this to this project, or give some pointers otherwise?

**Comment by dvalinotti** [comment]
Hi @tobi-or-not-tobi! 👋🏻

We would absolutely be open to contributions that would help quick-start projects with those features included. I myself have not explored SSR or routing methods with Lit but @herberthobregon  might know more. If you have specific options you want to include, or a new template that includes those features, you can fork this repo and make a PR to merge those changes here.

**Comment by herberthobregon** [comment]
Hi @tobi-or-not-tobi 😁

Of course, I will include more examples in the production template.

Currently [@conectate/ct-router](https://www.npmjs.com/package/@conectate/ct-router) is used as it has expressjs style expressions and handles dynamic imports, dynamic titles, login fallback, 404, auth req pages, etc. 🚀🔥. You can see the Docs in https://www.npmjs.com/package/@conectate/ct-router

I add JSDoc `@see` in `app-router` in `production-template` of this project

I haven't explored SSR because is a preview feature, but that I am sure would go on your backend server side that sends its PWA to the browser. So it is not in the scope of this project. 😔
You could choose multiple providers such as firebase, App Engine, AWS, Vercel, etc. to build your server and do SSR.

Ref. [https://www.npmjs.com/package/@lit-labs/ssr](https://www.npmjs.com/package/@lit-labs/ssr)

I working on add more doc on Readme in the root of project for `simple starter kit` and `production-template`. Anyone reading this can help 🔥

Let me know if you have questions about something and I can help you 🔥
